schema_version = "1.0.0"
id = "mpfb"
version = "2.0.6"
name = "MPFB"
tagline = "Human character generator and editor"
maintainer = "Joel Palmius"
type = "add-on"
website = "http://static.makehumancommunity.org/mpfb.html"
tags = ["Add mesh", "Modeling", "Rigging"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
files = "Load and save data"
network = "Interact with local instance of MakeHuman"

